name: "RedSock/PrCreator"
description: "Creates Pull Request on push to branch"

author: "RedSock"

branding:
  icon: "git-pull-request"
  color: "red"

inputs:
  pr-name-pattern:
    description: "Pattern for pull request name"
    default: "DEV RELEASE OF ${{ github.REF_NAME }}'"
  pr-body-pattern:
    description: "Pattern for pull request's body. Can accept markdown"
    default: "[${{ github.REF_NAME }}](https://redsock.youtrack.cloud/issue/${{ github.REF_NAME }})"
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: true
  target-branch:
    description: 'Target branch for pr'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Validation
      id: validation
      shell: bash
      run: |
        if [ -z "${{inputs.target-branch}}" ]; then
         echo "target-branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')" >> $GITHUB_OUTPUT
        else
          echo "target-branch=${{inputs.target-branch}}" >> $GITHUB_OUTPUT
        fi

    - name: Creating PR
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
      shell: bash
      run: |
        prs=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --json headRefName \
            --jq '
                map(select(.headRefName == "${{ github.REF_NAME }}"))
                | length
            ')
        
        echo "Found $prs pull request(s)"
        
        if (($prs == 0)); then
            echo "creating pull request from ${{ github.REF }} to branch ${{ steps.validation.outputs.target-branch }}"
        
            gh pr create \
              -B ${{ steps.validation.outputs.target-branch }} \
              -H ${{ github.REF }} \
              --title '${{ inputs.pr-name-pattern }}' \
              --body 'Created by RedSock action. ${{ inputs.pr-body-pattern }}'
        fi