name: "RedSock/PrCreator"
description: "Creates Pull Request on push to branch"

author: "RedSock"

branding:
  icon: "git-pull-request"
  color: "red"

inputs:
  pr-name-pattern:
    description: "Pattern for pull request name"
    default: "DEV RELEASE OF ${{ github.REF_NAME }}'"
  pr-body-pattern:
    description: "Pattern for pull request's body. Can accept markdown"
    default: "[${{ github.REF_NAME }}](https://redsock.youtrack.cloud/issue/${{ github.REF_NAME }})"
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Creating PR
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
      shell: bash
      run: |
        prs=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --json headRefName \
            --jq '
                map(select(.headRefName == "${{ github.REF_NAME }}"))
                | length
            ')
        
        echo "Found $prs pull request(s)"
        
        if (($prs == 0)); then
            echo "creating pull request from ${{ github.REF }} to dev branch"
        
            gh pr create \
              -B dev \
              -H ${{ github.REF }} \
              --title '${{ inputs.pr-name-pattern }}' \
              --body 'Created by RedSock action. \
              ${{ inputs.pr-body-pattern }}'
        fi