name: docs-actions
run-name: UpdateDocs
on:
  workflow_dispatch:
  push:
    branches:
      - redocs
jobs:
  redocs-launch:
    runs-on: ubuntu-latest
    steps:
      - uses: RedSockActions/redocs@v0.0.14
        with:
          token: ${{ github.token }}